//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalViews {
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.GlobalViews", typeof(GlobalViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        ///// <summary>
        /////   Looks up a localized string similar to Ad.
        ///// </summary>
        //public static string ad {
        //    get {
        //        return ResourceManager.GetString("ad", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Adres.
        ///// </summary>
        //public static string adres {
        //    get {
        //        return ResourceManager.GetString("adres", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Anasayfa.
        ///// </summary>
        //public static string anasayfa {
        //    get {
        //        return ResourceManager.GetString("anasayfa", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Banner Düzenle.
        ///// </summary>
        //public static string bannerDuzenle {
        //    get {
        //        return ResourceManager.GetString("bannerDuzenle", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Bilimsel Komite.
        ///// </summary>
        //public static string bilimselKomite {
        //    get {
        //        return ResourceManager.GetString("bilimselKomite", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Bir Sorun Oluştu.
        ///// </summary>
        //public static string birSorunOlustu {
        //    get {
        //        return ResourceManager.GetString("birSorunOlustu", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Durum.
        ///// </summary>
        //public static string durum {
        //    get {
        //        return ResourceManager.GetString("durum", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Editör.
        ///// </summary>
        //public static string editor {
        //    get {
        //        return ResourceManager.GetString("editor", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Eski Resim Silinecek.
        ///// </summary>
        //public static string eskiResimSilinecek {
        //    get {
        //        return ResourceManager.GetString("eskiResimSilinecek", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Etiket Adı Eng.
        ///// </summary>
        //public static string etiketAdiEng {
        //    get {
        //        return ResourceManager.GetString("etiketAdiEng", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Etiket Adı Tr.
        ///// </summary>
        //public static string etiketAdiTr {
        //    get {
        //        return ResourceManager.GetString("etiketAdiTr", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Genel.
        ///// </summary>
        //public static string genel {
        //    get {
        //        return ResourceManager.GetString("genel", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Genel Işlemler.
        ///// </summary>
        //public static string genelIslemler {
        //    get {
        //        return ResourceManager.GetString("genelIslemler", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Hakem.
        ///// </summary>
        //public static string hakem {
        //    get {
        //        return ResourceManager.GetString("hakem", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to İşlem Başarılı.
        ///// </summary>
        //public static string islemBasarili {
        //    get {
        //        return ResourceManager.GetString("islemBasarili", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Kapat.
        ///// </summary>
        //public static string kapat {
        //    get {
        //        return ResourceManager.GetString("kapat", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Kaydet.
        ///// </summary>
        //public static string kaydet {
        //    get {
        //        return ResourceManager.GetString("kaydet", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Konferans Tarihi.
        ///// </summary>
        //public static string konferansTarihi {
        //    get {
        //        return ResourceManager.GetString("konferansTarihi", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Konu Etiketi Düzenle.
        ///// </summary>
        //public static string konuEtiketiDuzenle {
        //    get {
        //        return ResourceManager.GetString("konuEtiketiDuzenle", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Kurum.
        ///// </summary>
        //public static string kurum {
        //    get {
        //        return ResourceManager.GetString("kurum", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Mail.
        ///// </summary>
        //public static string mail {
        //    get {
        //        return ResourceManager.GetString("mail", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Organizasyon Komite.
        ///// </summary>
        //public static string organizasyonKomite {
        //    get {
        //        return ResourceManager.GetString("organizasyonKomite", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Resim Yükleme Başarılı.
        ///// </summary>
        //public static string resimYuklemeBasarili {
        //    get {
        //        return ResourceManager.GetString("resimYuklemeBasarili", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Şehir.
        ///// </summary>
        //public static string sehir {
        //    get {
        //        return ResourceManager.GetString("sehir", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Soyad.
        ///// </summary>
        //public static string soyad {
        //    get {
        //        return ResourceManager.GetString("soyad", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Tamam.
        ///// </summary>
        //public static string tamam {
        //    get {
        //        return ResourceManager.GetString("tamam", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Tarih Güncellendi.
        ///// </summary>
        //public static string tarihGuncellendi {
        //    get {
        //        return ResourceManager.GetString("tarihGuncellendi", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Telefon.
        ///// </summary>
        //public static string telefon {
        //    get {
        //        return ResourceManager.GetString("telefon", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Ülke.
        ///// </summary>
        //public static string ulke {
        //    get {
        //        return ResourceManager.GetString("ulke", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Ünvan.
        ///// </summary>
        //public static string unvan {
        //    get {
        //        return ResourceManager.GetString("unvan", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Üye Düzenle.
        ///// </summary>
        //public static string uyeDuzenle {
        //    get {
        //        return ResourceManager.GetString("uyeDuzenle", resourceCulture);
        //    }
        //}

        ///// <summary>
        /////   Looks up a localized string similar to Yazar.
        ///// </summary>
        //public static string yazar {
        //    get {
        //        return ResourceManager.GetString("yazar", resourceCulture);
        //    }
        //}
    }
}
